In [1778]:
import pandas as pd

In [1779]:
%run funcoes_gerais.ipynb

In [1780]:
cod_municipios = pd.read_csv('../dataset/Código dos Municípios')

In [1781]:
caged = pd.read_excel("../dataset/Economico/Renda e Desenvolvimento/PIB/caged_Atualizado.xlsx")

In [1782]:
bolsa_familia = pd.read_csv("../dataset/Social/Projetos Sociais/Bolsa_Familia_2024.csv")
bpc = pd.read_csv("../dataset/Social/Projetos Sociais/bpc_2024.csv")

In [1783]:
clin_Amb_BAS = pd.read_csv("../dataset/Condicao de Saude Tipico/Infraestrutura/Numero de clinicas Basicas/CNES_Ambulatorio_basico_2024.csv", encoding='latin-1', skiprows=3, sep=';')
clin_Amb_ESP = pd.read_csv("../dataset/Condicao de Saude Tipico/Infraestrutura/Numero de clinicas especializadas/CNES_Ambulatorio_Esp_2024.csv", encoding='latin-1', skiprows=3, sep=';')

In [1784]:
leitos_internacao = pd.read_csv("../dataset/Condicao de Saude Tipico/Infraestrutura/numero de Leitos/CNES_Leitos_Internação_Hospitalar_2024.csv",encoding='latin-1', skiprows=3, sep=';')

In [1785]:
leitos_repouso_Ambulatorio_FEM = pd.read_csv("../dataset/Condicao de Saude Tipico/Infraestrutura/numero de Leitos/CNES_Leitos_repouso_Ambulatorio_FEM_2024.csv",encoding='latin-1', skiprows=3, sep=';')
leitos_repouso_Ambulatorio_INDF = pd.read_csv("../dataset/Condicao de Saude Tipico/Infraestrutura/numero de Leitos/CNES_Leitos_repouso_Ambulatorio_INDF_2024.csv",encoding='latin-1', skiprows=3, sep=';')
leitos_repouso_Ambulatorio_MASC = pd.read_csv("../dataset/Condicao de Saude Tipico/Infraestrutura/numero de Leitos/CNES_Leitos_repouso_Ambulatorio_MASC_2024.csv",encoding='latin-1', skiprows=3, sep=';')
leitos_repouso_Ambulatorio_PED = pd.read_csv("../dataset/Condicao de Saude Tipico/Infraestrutura/numero de Leitos/CNES_Leitos_repouso_Ambulatorio_PED_2024.csv",encoding='latin-1', skiprows=3, sep=';')

In [1786]:
leitos_repouso_Urgencia_FEM = pd.read_csv("../dataset/Condicao de Saude Tipico/Infraestrutura/numero de Leitos/CNES_Leitos_repouso_Urgencia_FEM_2024.csv",encoding='latin-1', skiprows=3, sep=';')
leitos_repouso_Urgencia_INDF = pd.read_csv("../dataset/Condicao de Saude Tipico/Infraestrutura/numero de Leitos/CNES_Leitos_repouso_Urgencia_INDF_2024.csv",encoding='latin-1', skiprows=3, sep=';')
leitos_repouso_Urgencia_MASC = pd.read_csv("../dataset/Condicao de Saude Tipico/Infraestrutura/numero de Leitos/CNES_Leitos_repouso_Urgencia_MASC_2024.csv",encoding='latin-1', skiprows=3, sep=';')
leitos_repouso_Urgencia_PED = pd.read_csv("../dataset/Condicao de Saude Tipico/Infraestrutura/numero de Leitos/CNES_Leitos_repouso_Urgencia_PED_2024.csv",encoding='latin-1', skiprows=3, sep=';')

# Analise

### CNES

#### Amb_BAS

In [1787]:
clin_Amb_BAS

,Município,2024/Jan,2024/Fev,2024/Mar,2024/Abr,2024/Mai,2024/Jun,2024/Jul,2024/Ago,2024/Set,2024/Out,2024/Nov,2024/Dez
0,110001 ALTA FLORESTA D'OESTE,36,36,36,36,37,38,39,39,39,39,39,39
1,110002 ARIQUEMES,80,82,83,83,83,84,85,87,89,89,89,90
2,110003 CABIXI,8,8,8,8,8,8,8,8,8,8,8,8
3,110004 CACOAL,236,238,238,239,239,241,243,244,244,244,245,248
4,110005 CEREJEIRAS,12,12,12,12,12,12,12,12,12,12,12,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5426,- Os dados relativos ao Cadastro Nacional de ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5427,"- A partir do processamento de junho de 2012,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5428,Até maio de 2012 estas informações estão disp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5429,"De junho de 2012 a outubro de 2015, estão dis...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5430,"A partir de novembro de 2015, estão disponíve...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1788]:
clin_Amb_BAS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5431 entries, 0 to 5430
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Município  5431 non-null   object
 1   2024/Jan   5424 non-null   object
 2   2024/Fev   5424 non-null   object
 3   2024/Mar   5424 non-null   object
 4   2024/Abr   5424 non-null   object
 5   2024/Mai   5424 non-null   object
 6   2024/Jun   5424 non-null   object
 7   2024/Jul   5424 non-null   object
 8   2024/Ago   5424 non-null   object
 9   2024/Set   5424 non-null   object
 10  2024/Out   5424 non-null   object
 11  2024/Nov   5424 non-null   object
 12  2024/Dez   5424 non-null   object
dtypes: object(13)
memory usage: 551.7+ KB

In [1789]:
clin_Amb_BAS.columns

Index(['Município', '2024/Jan', '2024/Fev', '2024/Mar', '2024/Abr', '2024/Mai',
       '2024/Jun', '2024/Jul', '2024/Ago', '2024/Set', '2024/Out', '2024/Nov',
       '2024/Dez'],
      dtype='object')

#### Amb_Esp

In [1790]:
clin_Amb_ESP

,Município,2024/Jan,2024/Fev,2024/Mar,2024/Abr,2024/Mai,2024/Jun,2024/Jul,2024/Ago,2024/Set,2024/Out,2024/Nov,2024/Dez
0,110001 ALTA FLORESTA D'OESTE,7,7,7,7,7,7,7,7,7,7,7,7
1,110002 ARIQUEMES,101,101,102,102,101,102,106,106,107,107,108,108
2,110004 CACOAL,161,161,162,162,165,165,165,165,165,164,166,166
3,110005 CEREJEIRAS,8,8,8,8,8,9,10,10,10,10,10,9
4,110006 COLORADO DO OESTE,3,4,4,4,4,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4115,- Os dados relativos ao Cadastro Nacional de ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4116,"- A partir do processamento de junho de 2012,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4117,Até maio de 2012 estas informações estão disp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4118,"De junho de 2012 a outubro de 2015, estão dis...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4119,"A partir de novembro de 2015, estão disponíve...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1791]:
clin_Amb_ESP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4120 entries, 0 to 4119
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Município  4120 non-null   object
 1   2024/Jan   4113 non-null   object
 2   2024/Fev   4113 non-null   object
 3   2024/Mar   4113 non-null   object
 4   2024/Abr   4113 non-null   object
 5   2024/Mai   4113 non-null   object
 6   2024/Jun   4113 non-null   object
 7   2024/Jul   4113 non-null   object
 8   2024/Ago   4113 non-null   object
 9   2024/Set   4113 non-null   object
 10  2024/Out   4113 non-null   object
 11  2024/Nov   4113 non-null   object
 12  2024/Dez   4113 non-null   object
dtypes: object(13)
memory usage: 418.6+ KB

#### Internação

In [1792]:
leitos_internacao

,Município,2024/Jan,2024/Fev,2024/Mar,2024/Abr,2024/Mai,2024/Jun,2024/Jul,2024/Ago,2024/Set,2024/Out,2024/Nov,2024/Dez
0,110001 ALTA FLORESTA D'OESTE,55,55,55,55,55,55,55,55,55,55,55,55
1,110002 ARIQUEMES,257,257,257,257,257,257,257,260,260,264,264,270
2,110003 CABIXI,8,8,8,8,8,8,8,8,8,8,8,8
3,110004 CACOAL,400,407,407,407,407,416,418,418,418,418,421,421
4,110005 CEREJEIRAS,40,40,40,40,40,40,40,40,40,40,40,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3622,- Os dados relativos ao Cadastro Nacional de ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3623,"- A partir do processamento de junho de 2012,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3624,Até maio de 2012 estas informações estão disp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3625,"De junho de 2012 a outubro de 2015, estão dis...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3626,"A partir de novembro de 2015, estão disponíve...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1793]:
leitos_internacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3627 entries, 0 to 3626
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Município  3627 non-null   object
 1   2024/Jan   3617 non-null   object
 2   2024/Fev   3617 non-null   object
 3   2024/Mar   3617 non-null   object
 4   2024/Abr   3617 non-null   object
 5   2024/Mai   3617 non-null   object
 6   2024/Jun   3617 non-null   object
 7   2024/Jul   3617 non-null   object
 8   2024/Ago   3617 non-null   object
 9   2024/Set   3617 non-null   object
 10  2024/Out   3617 non-null   object
 11  2024/Nov   3617 non-null   object
 12  2024/Dez   3617 non-null   object
dtypes: object(13)
memory usage: 368.5+ KB

#### Leito Amb

In [1794]:
leitos_repouso_Ambulatorio_FEM

,Município,2024/Jan,2024/Fev,2024/Mar,2024/Abr,2024/Mai,2024/Jun,2024/Jul,2024/Ago,2024/Set,2024/Out,2024/Nov,2024/Dez
0,110004 CACOAL,4,4,4,4,4,4,4,4,4,4,4,4
1,110007 CORUMBIARA,5,5,5,5,5,5,5,5,5,5,5,5
2,110011 JARU,1,1,1,1,1,1,1,1,1,1,1,1
3,110020 PORTO VELHO,9,9,9,9,9,9,9,9,9,9,9,9
4,110028 ROLIM DE MOURA,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527,- Os dados relativos ao Cadastro Nacional de ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1528,"- A partir do processamento de junho de 2012,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1529,Até maio de 2012 estas informações estão disp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1530,"De junho de 2012 a outubro de 2015, estão dis...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1531,"A partir de novembro de 2015, estão disponíve...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1795]:
leitos_repouso_Ambulatorio_FEM.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1532 entries, 0 to 1531
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Município  1532 non-null   object
 1   2024/Jan   1525 non-null   object
 2   2024/Fev   1525 non-null   object
 3   2024/Mar   1525 non-null   object
 4   2024/Abr   1525 non-null   object
 5   2024/Mai   1525 non-null   object
 6   2024/Jun   1525 non-null   object
 7   2024/Jul   1525 non-null   object
 8   2024/Ago   1525 non-null   object
 9   2024/Set   1525 non-null   object
 10  2024/Out   1525 non-null   object
 11  2024/Nov   1525 non-null   object
 12  2024/Dez   1525 non-null   object
dtypes: object(13)
memory usage: 155.7+ KB

#### Leito Urg

In [1796]:
leitos_repouso_Urgencia_INDF

,Município,2024/Jan,2024/Fev,2024/Mar,2024/Abr,2024/Mai,2024/Jun,2024/Jul,2024/Ago,2024/Set,2024/Out,2024/Nov,2024/Dez
0,110001 ALTA FLORESTA D'OESTE,4,4,4,4,4,4,4,4,4,4,4,4
1,110002 ARIQUEMES,16,16,16,16,16,16,16,16,16,16,16,16
2,110003 CABIXI,3,3,3,3,3,3,3,3,3,3,3,3
3,110004 CACOAL,28,28,28,28,28,28,28,28,28,28,28,29
4,110005 CEREJEIRAS,1,1,1,1,1,1,4,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2517,- Os dados relativos ao Cadastro Nacional de ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2518,"- A partir do processamento de junho de 2012,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2519,Até maio de 2012 estas informações estão disp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2520,"De junho de 2012 a outubro de 2015, estão dis...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2521,"A partir de novembro de 2015, estão disponíve...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1797]:
leitos_repouso_Urgencia_INDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2522 entries, 0 to 2521
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Município  2522 non-null   object
 1   2024/Jan   2515 non-null   object
 2   2024/Fev   2515 non-null   object
 3   2024/Mar   2515 non-null   object
 4   2024/Abr   2515 non-null   object
 5   2024/Mai   2515 non-null   object
 6   2024/Jun   2515 non-null   object
 7   2024/Jul   2515 non-null   object
 8   2024/Ago   2515 non-null   object
 9   2024/Set   2515 non-null   object
 10  2024/Out   2515 non-null   object
 11  2024/Nov   2515 non-null   object
 12  2024/Dez   2515 non-null   object
dtypes: object(13)
memory usage: 256.3+ KB

### Caged

In [1798]:
caged

,Codigo_Municipio,Codigo_Municipio_2,UF,Municipio,2020_Estoque_media,2020_Estoque_MAX,2020_Estoque_MIN,2023_Estoque_media,2023_Estoque_MAX,2023_Estoque_MIN,...,2022_Estoque_MAX,2022_Estoque_MIN,2021_Estoque_media,2021_Estoque_MAX,2021_Estoque_MIN,2024_Estoque_media,2024_Estoque_MAX,2024_Estoque_MIN,UF.1,Municipio.1
0,1100015,110001,RO,Alta Floresta D Oeste,"1,964.69","2,024.00","1,915.00","2,272.17","2,334.00","2,208.00",...,"2,269.00","2,107.00","2,096.67","2,134.00","2,045.00","2,294.00","2,298.00","2,290.00",RO,Alta Floresta D Oeste
1,1100379,110037,RO,Alto Alegre dos Parecis,560.56,576.00,549.00,675.42,697.00,653.00,...,686.00,575.00,589.25,606.00,571.00,692.00,700.00,684.00,RO,Alto Alegre dos Parecis
2,1100403,110040,RO,Alto Paraiso,"1,193.02","1,233.00","1,165.00","1,277.00","1,310.00","1,216.00",...,"1,288.00","1,240.00","1,240.50","1,275.00","1,193.00","1,247.00","1,255.00","1,239.00",RO,Alto Paraiso
3,1100346,110034,RO,Alvorada D Oeste,807.90,827.00,785.00,872.42,899.00,861.00,...,922.00,882.00,877.92,897.00,848.00,867.00,869.00,865.00,RO,Alvorada D Oeste
4,1100023,110002,RO,Ariquemes,"15,949.64","16,308.00","15,508.00","19,121.75","19,513.00","18,246.00",...,"19,031.00","17,539.00","16,900.17","17,517.00","16,221.00","19,150.00","19,500.00","18,800.00",RO,Ariquemes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,5222005,522200,GO,Vianopolis,"2,125.08","2,171.00","2,091.00","2,833.58","2,981.00","2,674.00",...,"2,743.00","2,551.00","2,346.42","2,504.00","2,198.00","2,972.00","2,980.00","2,964.00",GO,Vianopolis
5566,5222054,522205,GO,Vicentinopolis,"2,367.00","2,549.00","2,052.00","2,529.00","2,794.00","2,163.00",...,"2,671.00","1,991.00","2,318.17","2,563.00","1,963.00","2,311.50","2,361.00","2,262.00",GO,Vicentinopolis
5567,5222203,522220,GO,Vila Boa,"1,750.04","2,052.00","1,524.00","1,785.00","2,169.00","1,312.00",...,"2,347.00","1,429.00","1,787.25","2,152.00","1,369.00","1,410.00","1,422.00","1,398.00",GO,Vila Boa
5568,5222302,522230,GO,Vila Propicio,936.63,956.00,914.00,"1,178.42","1,245.00","1,132.00",...,"1,152.00","1,044.00","1,022.67","1,048.00",968.00,"1,146.00","1,158.00","1,134.00",GO,Vila Propicio
5569,5300108,530010,DF,Brasilia,"827,892.78","847,945.00","814,709.00","954,068.33","973,513.00","929,370.00",...,"938,715.00","887,395.00","858,208.17","887,440.00","833,296.00","973,895.50","977,151.00","970,640.00",DF,Brasilia

In [1799]:
caged = caged[['Codigo_Municipio', '2024_Estoque_media', '2024_Estoque_MAX', '2024_Estoque_MIN']]

In [1800]:
caged

      Codigo_Municipio  2024_Estoque_media  2024_Estoque_MAX  2024_Estoque_MIN
0              1100015            2,294.00          2,298.00          2,290.00
1              1100379              692.00            700.00            684.00
2              1100403            1,247.00          1,255.00          1,239.00
3              1100346              867.00            869.00            865.00
4              1100023           19,150.00         19,500.00         18,800.00
...                ...                 ...               ...               ...
5565           5222005            2,972.00          2,980.00          2,964.00
5566           5222054            2,311.50          2,361.00          2,262.00
5567           5222203            1,410.00          1,422.00          1,398.00
5568           5222302            1,146.00          1,158.00          1,134.00
5569           5300108          973,895.50        977,151.00        970,640.00

[5570 rows x 4 columns]

### BPC

In [1801]:
bpc

,ibge,anomes,bpc_ben,bpc_pcd_ben,bpc_idoso_ben,bpc_pcd_val,bpc_idoso_val,bpc_val
0,110001,202401,582,471.00,111.00,"665,060.19","156,732.00","821,792.19"
1,110002,202401,3468,"2,255.00","1,213.00","3,185,546.17","1,712,764.14","4,898,310.31"
2,110003,202401,86,65.00,21.00,"91,781.70","29,652.00","121,433.70"
3,110004,202401,2428,"1,716.00",712.00,"2,423,047.32","1,005,350.11","3,428,397.43"
4,110005,202401,482,372.00,110.00,"525,272.00","155,320.20","680,592.20"
...,...,...,...,...,...,...,...,...
61265,522200,202411,0,NaN,NaN,NaN,NaN,0.00
61266,522205,202411,0,NaN,NaN,NaN,NaN,0.00
61267,522220,202411,0,NaN,NaN,NaN,NaN,0.00
61268,522230,202411,0,NaN,NaN,NaN,NaN,0.00
61269,530010,202411,0,NaN,NaN,NaN,NaN,0.00

In [1802]:
bpc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61270 entries, 0 to 61269
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ibge           61270 non-null  int64
 1   anomes         61270 non-null  int64
 2   bpc_ben        61270 non-null  int64
 3   bpc_pcd_ben    50125 non-null  float64
 4   bpc_idoso_ben  50125 non-null  float64
 5   bpc_pcd_val    50124 non-null  float64
 6   bpc_idoso_val  49937 non-null  float64
 7   bpc_val        61270 non-null  float64
dtypes: float64(5), int64(3)
memory usage: 3.7 MB

In [1803]:
bpc['anomes'].value_counts()

anomes
202401    5570
202402    5570
202403    5570
202404    5570
202405    5570
202406    5570
202407    5570
202408    5570
202409    5570
202410    5570
202411    5570
Name: count, dtype: int64

### Bolsa Familia

In [1804]:
bolsa_familia

,codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f
0,110001,202411,1680,"1,137,432.00",681.10
1,110002,202411,7532,"5,144,552.00",686.49
2,110003,202411,302,"202,592.00",670.83
3,110004,202411,6067,"4,035,378.00",665.79
4,110005,202411,1213,"846,900.00",700.50
...,...,...,...,...,...
61265,522200,202401,1086,"752,035.00",692.48
61266,522205,202401,806,"554,559.00",688.04
61267,522220,202401,630,"433,991.00",688.87
61268,522230,202401,756,"509,345.00",673.74
61269,530010,202401,194735,"134,208,133.00",689.18

In [1805]:
bolsa_familia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61270 entries, 0 to 61269
Data columns (total 5 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   codigo_ibge                                 61270 non-null  int64
 1   anomes_s                                    61270 non-null  int64
 2   qtd_familias_beneficiarias_bolsa_familia_s  61270 non-null  int64
 3   valor_repassado_bolsa_familia_s             61270 non-null  float64
 4   pbf_vlr_medio_benef_f                       61270 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 2.3 MB

In [1806]:
bolsa_familia.rename(columns={'anomes_s': 'anomes', 'codigo_ibge':'ibge', 'qtd_familias_beneficiarias_bolsa_familia_s':'qtd_familias_beneficiarias_bolsa_familia', 'valor_repassado_bolsa_familia_s': 'valor_repassado_bolsa_familia'}, inplace=True)

In [1807]:
bolsa_familia['anomes'].value_counts()

anomes
202411    5570
202410    5570
202409    5570
202408    5570
202407    5570
202406    5570
202405    5570
202404    5570
202403    5570
202402    5570
202401    5570
Name: count, dtype: int64

# Transformação

### CNES

#### Amb_BAS

In [1808]:
clin_Amb_BAS = CNES(clin_Amb_BAS)

/tmp/ipykernel_18806/1269023033.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace('-', np.nan, inplace=True)
/tmp/ipykernel_18806/1269023033.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df.columns] =  df[df.columns].astype(float)

In [1809]:
clin_Amb_BAS.rename(columns={'sum':'Numero Clinicas de Ambulatorio Basicas'}, inplace=True)

In [1810]:
clin_Amb_BAS

      cod_municipio  Numero Clinicas de Ambulatorio Basicas
0        110,001.00                                  453.00
1        110,002.00                                1,024.00
2        110,003.00                                   96.00
3        110,004.00                                2,899.00
4        110,005.00                                  144.00
...             ...                                     ...
5418     522,200.00                                   36.00
5419     522,205.00                                  120.00
5420     522,220.00                                   72.00
5421     522,230.00                                   24.00
5422     530,010.00                               30,448.00

[5423 rows x 2 columns]

#### AMB_ESP

In [1811]:
clin_Amb_ESP = CNES(clin_Amb_ESP)

/tmp/ipykernel_18806/1269023033.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace('-', np.nan, inplace=True)
/tmp/ipykernel_18806/1269023033.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df.columns] =  df[df.columns].astype(float)

In [1812]:
clin_Amb_ESP.rename(columns={'sum':'Numero Clinicas de Ambulatorio Especializadas'}, inplace=True)

In [1813]:
clin_Amb_ESP

      cod_municipio  Numero Clinicas de Ambulatorio Especializadas
0        110,001.00                                          84.00
1        110,002.00                                       1,251.00
2        110,004.00                                       1,967.00
3        110,005.00                                         108.00
4        110,006.00                                          47.00
...             ...                                            ...
4107     522,170.00                                          83.00
4108     522,180.00                                          36.00
4109     522,185.00                                         594.00
4110     522,200.00                                          24.00
4111     530,010.00                                      73,932.00

[4112 rows x 2 columns]

#### Internação

In [1814]:
leitos_internacao = CNES(leitos_internacao)

/tmp/ipykernel_18806/1269023033.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace('-', np.nan, inplace=True)
/tmp/ipykernel_18806/1269023033.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df.columns] =  df[df.columns].astype(float)

In [1815]:
leitos_internacao.rename(columns={'sum':'Numero Leitos de Internação'}, inplace=True)

In [1816]:
leitos_internacao

      cod_municipio  Numero Leitos de Internação
0        110,001.00                       660.00
1        110,002.00                     3,117.00
2        110,003.00                        96.00
3        110,004.00                     4,958.00
4        110,005.00                       480.00
...             ...                          ...
3611     522,185.00                       882.00
3612     522,200.00                       480.00
3613     522,205.00                       192.00
3614     522,220.00                       156.00
3615     530,010.00                    96,106.00

[3616 rows x 2 columns]

#### Leito Amb

In [1817]:
leitos_repouso_Ambulatorio_FEM = CNES(leitos_repouso_Ambulatorio_FEM)
leitos_repouso_Ambulatorio_INDF = CNES(leitos_repouso_Ambulatorio_INDF)
leitos_repouso_Ambulatorio_MASC = CNES(leitos_repouso_Ambulatorio_MASC)
leitos_repouso_Ambulatorio_PED = CNES(leitos_repouso_Ambulatorio_PED)

/tmp/ipykernel_18806/1269023033.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace('-', np.nan, inplace=True)
/tmp/ipykernel_18806/1269023033.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df.columns] =  df[df.columns].astype(float)
/tmp/ipykernel_18806/1269023033.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace('-', np.nan, inplace=True)
/tmp/ipykernel_18806/1269023033.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df.columns] =  df[df.columns].astype(float)
/tmp/ipykernel_18806/1269023033.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace('-', np.nan, inplace=True)
/tmp/ipykernel_18806/1269023033.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df.columns] =  df[df.columns].astype(float)
/tmp/ipykernel_18806/1269023033.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace('-', np.nan, inplace=True)
/tmp/ipykernel_18806/1269023033.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df.columns] =  df[df.columns].astype(float)

In [1818]:
leitos_repouso_Ambulatorio_FEM.rename(columns={'sum':'Numero Leitos de Ambulatorio Feminino'}, inplace=True)
leitos_repouso_Ambulatorio_INDF.rename(columns={'sum':'Numero Leitos de Ambulatorio Indiferente'}, inplace=True)
leitos_repouso_Ambulatorio_MASC.rename(columns={'sum':'Numero Leitos de Ambulatorio Masculino'}, inplace=True)
leitos_repouso_Ambulatorio_PED.rename(columns={'sum':'Numero Leitos de Ambulatorio Pediatro'}, inplace=True)

In [1819]:
leitos_repouso_Ambulatorio_FEM

      cod_municipio  Numero Leitos de Ambulatorio Feminino
0        110,004.00                                  48.00
1        110,007.00                                  60.00
2        110,011.00                                  12.00
3        110,020.00                                 108.00
4        110,028.00                                  12.00
...             ...                                    ...
1519     522,157.00                                  48.00
1520     522,160.00                                  12.00
1521     522,180.00                                  24.00
1522     522,200.00                                  48.00
1523     530,010.00                                 192.00

[1524 rows x 2 columns]

In [1820]:
leitos_repouso_Ambulatorio_INDF

      cod_municipio  Numero Leitos de Ambulatorio Indiferente
0        110,002.00                                    272.00
1        110,003.00                                     24.00
2        110,004.00                                    576.00
3        110,005.00                                     55.00
4        110,008.00                                     24.00
...             ...                                       ...
3659     522,160.00                                     60.00
3660     522,185.00                                    110.00
3661     522,200.00                                     36.00
3662     522,205.00                                     24.00
3663     530,010.00                                  2,132.00

[3664 rows x 2 columns]

In [1821]:
leitos_repouso_Ambulatorio_MASC

      cod_municipio  Numero Leitos de Ambulatorio Masculino
0        110,002.00                                  272.00
1        110,003.00                                   24.00
2        110,004.00                                  576.00
3        110,005.00                                   55.00
4        110,008.00                                   24.00
...             ...                                     ...
3659     522,160.00                                   60.00
3660     522,185.00                                  110.00
3661     522,200.00                                   36.00
3662     522,205.00                                   24.00
3663     530,010.00                                2,132.00

[3664 rows x 2 columns]

In [1822]:
leitos_repouso_Ambulatorio_PED

      cod_municipio  Numero Leitos de Ambulatorio Pediatro
0        110,002.00                                 272.00
1        110,003.00                                  24.00
2        110,004.00                                 576.00
3        110,005.00                                  55.00
4        110,008.00                                  24.00
...             ...                                    ...
3659     522,160.00                                  60.00
3660     522,185.00                                 110.00
3661     522,200.00                                  36.00
3662     522,205.00                                  24.00
3663     530,010.00                               2,132.00

[3664 rows x 2 columns]

#### Leito Urg

In [1823]:
leitos_repouso_Urgencia_FEM = CNES(leitos_repouso_Urgencia_FEM)
leitos_repouso_Urgencia_INDF = CNES(leitos_repouso_Urgencia_INDF)
leitos_repouso_Urgencia_MASC = CNES(leitos_repouso_Urgencia_MASC)
leitos_repouso_Urgencia_PED = CNES(leitos_repouso_Urgencia_PED)

/tmp/ipykernel_18806/1269023033.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace('-', np.nan, inplace=True)
/tmp/ipykernel_18806/1269023033.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df.columns] =  df[df.columns].astype(float)
/tmp/ipykernel_18806/1269023033.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace('-', np.nan, inplace=True)
/tmp/ipykernel_18806/1269023033.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df.columns] =  df[df.columns].astype(float)
/tmp/ipykernel_18806/1269023033.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace('-', np.nan, inplace=True)
/tmp/ipykernel_18806/1269023033.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df.columns] =  df[df.columns].astype(float)
/tmp/ipykernel_18806/1269023033.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace('-', np.nan, inplace=True)
/tmp/ipykernel_18806/1269023033.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df.columns] =  df[df.columns].astype(float)

In [1824]:
leitos_repouso_Urgencia_FEM.rename(columns={'sum':'Numero Leitos de Urgencia Feminino'}, inplace=True)
leitos_repouso_Urgencia_INDF.rename(columns={'sum':'Numero Leitos de Urgencia Indiferente'}, inplace=True)
leitos_repouso_Urgencia_MASC.rename(columns={'sum':'Numero Leitos de Urgencia Masculino'}, inplace=True)
leitos_repouso_Urgencia_PED.rename(columns={'sum':'Numero Leitos de Urgencia Pediatro'}, inplace=True)

In [1825]:
leitos_repouso_Urgencia_FEM

      cod_municipio  Numero Leitos de Urgencia Feminino
0        110,001.00                               24.00
1        110,002.00                               30.00
2        110,004.00                               30.00
3        110,005.00                               24.00
4        110,011.00                               24.00
...             ...                                 ...
2468     522,157.00                               12.00
2469     522,160.00                               54.00
2470     522,170.00                               12.00
2471     522,180.00                               24.00
2472     530,010.00                            2,086.00

[2473 rows x 2 columns]

In [1826]:
leitos_repouso_Urgencia_INDF

      cod_municipio  Numero Leitos de Urgencia Indiferente
0        110,001.00                                  48.00
1        110,002.00                                 192.00
2        110,003.00                                  36.00
3        110,004.00                                 337.00
4        110,005.00                                  15.00
...             ...                                    ...
2509     522,155.00                                  12.00
2510     522,160.00                                  70.00
2511     522,185.00                                 312.00
2512     522,220.00                                  12.00
2513     530,010.00                              11,304.00

[2514 rows x 2 columns]

In [1827]:
leitos_repouso_Urgencia_MASC

      cod_municipio  Numero Leitos de Urgencia Masculino
0        110,002.00                                34.00
1        110,004.00                                 6.00
2        110,005.00                                24.00
3        110,006.00                                20.00
4        110,007.00                                12.00
...             ...                                  ...
2409     522,157.00                                12.00
2410     522,160.00                                59.00
2411     522,170.00                                24.00
2412     522,180.00                                24.00
2413     530,010.00                             1,275.00

[2414 rows x 2 columns]

In [1828]:
leitos_repouso_Urgencia_PED

      cod_municipio  Numero Leitos de Urgencia Pediatro
0        110,002.00                               34.00
1        110,004.00                                6.00
2        110,005.00                               24.00
3        110,006.00                               20.00
4        110,007.00                               12.00
...             ...                                 ...
2409     522,157.00                               12.00
2410     522,160.00                               59.00
2411     522,170.00                               24.00
2412     522,180.00                               24.00
2413     530,010.00                            1,275.00

[2414 rows x 2 columns]

### Caged

In [1829]:
caged = caged.round(2)

In [1830]:
caged

      Codigo_Municipio  2024_Estoque_media  2024_Estoque_MAX  2024_Estoque_MIN
0              1100015            2,294.00          2,298.00          2,290.00
1              1100379              692.00            700.00            684.00
2              1100403            1,247.00          1,255.00          1,239.00
3              1100346              867.00            869.00            865.00
4              1100023           19,150.00         19,500.00         18,800.00
...                ...                 ...               ...               ...
5565           5222005            2,972.00          2,980.00          2,964.00
5566           5222054            2,311.50          2,361.00          2,262.00
5567           5222203            1,410.00          1,422.00          1,398.00
5568           5222302            1,146.00          1,158.00          1,134.00
5569           5300108          973,895.50        977,151.00        970,640.00

[5570 rows x 4 columns]

### BPC

In [1831]:
bpc = BPC(bpc)

In [1832]:
bpc

,ibge,num_beneficiados_bpc,media_beneficiados_bpc,num_pcd_beneficiados_bpc,media_pcd_beneficiados_bpc,num_idoso_beneficiados_bpc,media_idoso_beneficiados_bpc,valor_total_repassado_bpc,media_valor_repassado_bpc,valor_pcd_repassado_bpc,media_valor_pcd_repassado_bpc,valor_idoso_repassado_bpc,media_valor_idoso_repassado_pbc
0,110001,5494,499.45,"4,482.00",498.00,"1,012.00",112.44,"7,757,639.41","705,239.95","6,328,691.21","703,187.91","1,428,948.20","158,772.02"
1,110002,32604,"2,964.00","21,411.00","2,379.00","11,193.00","1,243.67","46,054,015.71","4,186,728.70","30,236,667.06","3,359,629.67","15,817,348.65","1,757,483.18"
2,110003,808,73.45,613.00,68.11,195.00,21.67,"1,140,915.17","103,719.56","865,573.59","96,174.84","275,341.58","30,593.51"
3,110004,22440,"2,040.00","15,969.00","1,774.33","6,471.00",719.00,"31,694,497.95","2,881,318.00","22,554,538.33","2,506,059.81","9,139,959.62","1,015,551.07"
4,110005,4577,416.09,"3,504.00",389.33,"1,073.00",119.22,"6,464,217.06","587,656.10","4,947,727.33","549,747.48","1,516,489.73","168,498.86"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,522200,3419,310.82,"1,965.00",218.33,"1,454.00",161.56,"4,827,666.78","438,878.80","2,774,608.36","308,289.82","2,053,058.42","228,117.60"
5566,522205,1334,121.27,876.00,97.33,458.00,50.89,"1,883,670.80","171,242.80","1,236,966.15","137,440.68","646,704.65","71,856.07"
5567,522220,1284,116.73,977.00,108.56,307.00,34.11,"1,813,021.34","164,820.12","1,379,534.34","153,281.59","433,487.00","48,165.22"
5568,522230,463,42.09,377.00,41.89,86.00,9.56,"653,769.49","59,433.59","532,333.89","59,148.21","121,435.60","13,492.84"
5569,530010,647731,"58,884.64","345,308.00","38,367.56","302,423.00","33,602.56","914,960,165.59","83,178,196.87","487,748,691.92","54,194,299.10","427,211,473.67","47,467,941.52"

### Bolsa Familia

In [1833]:
bolsa_familia = Bolsa_Familia(bolsa_familia)

In [1834]:
bolsa_familia

,ibge,qtd_familias_total_bolsa_familia,media_qtd_familias_bolsa_familia,valor_total_repassado_bolsa_familia,media_valor_repassado_bolsa_familia
0,110001,18616,"1,692.36","12,804,296.00","1,164,026.91"
1,110002,79740,"7,249.09","54,233,194.00","4,930,290.36"
2,110003,3498,318.00,"2,321,626.00","211,056.91"
3,110004,66039,"6,003.55","44,217,871.00","4,019,806.45"
4,110005,12906,"1,173.27","9,146,838.00","831,530.73"
...,...,...,...,...,...
5565,522200,11734,"1,066.73","7,995,392.00","726,853.82"
5566,522205,8911,810.09,"6,056,026.00","550,547.82"
5567,522220,7015,637.73,"4,807,678.00","437,061.64"
5568,522230,8348,758.91,"5,564,729.00","505,884.45"
5569,530010,2032446,"184,767.82","1,390,106,282.00","126,373,298.36"

In [1835]:
bolsa_familia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 5 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ibge                                 5570 non-null   int64
 1   qtd_familias_total_bolsa_familia     5570 non-null   int64
 2   media_qtd_familias_bolsa_familia     5570 non-null   float64
 3   valor_total_repassado_bolsa_familia  5570 non-null   float64
 4   media_valor_repassado_bolsa_familia  5570 non-null   float64
dtypes: float64(3), int64(2)
memory usage: 217.7 KB

# Integração

In [1836]:
bd_2024 = cod_municipios[['Codigo_Municipio', 'Codigo_Municipio_2', 'Município', 'UF', 'Sigla_UF']]

In [1837]:
bd_2024 = bd_2024.merge(caged, how='left')

In [1838]:
bd_2024

,Codigo_Municipio,Codigo_Municipio_2,Município,UF,Sigla_UF,2024_Estoque_media,2024_Estoque_MAX,2024_Estoque_MIN
0,1100015,110001,Alta Floresta D'Oeste,11,RO,"2,294.00","2,298.00","2,290.00"
1,1100379,110037,Alto Alegre dos Parecis,11,RO,692.00,700.00,684.00
2,1100403,110040,Alto Paraíso,11,RO,"1,247.00","1,255.00","1,239.00"
3,1100346,110034,Alvorada D'Oeste,11,RO,867.00,869.00,865.00
4,1100023,110002,Ariquemes,11,RO,"19,150.00","19,500.00","18,800.00"
...,...,...,...,...,...,...,...,...
5565,5222005,522200,Vianópolis,52,GO,"2,972.00","2,980.00","2,964.00"
5566,5222054,522205,Vicentinópolis,52,GO,"2,311.50","2,361.00","2,262.00"
5567,5222203,522220,Vila Boa,52,GO,"1,410.00","1,422.00","1,398.00"
5568,5222302,522230,Vila Propício,52,GO,"1,146.00","1,158.00","1,134.00"
5569,5300108,530010,Brasília,53,DF,"973,895.50","977,151.00","970,640.00"

In [1839]:
bd_2024 = bd_2024.merge(clin_Amb_BAS, how='left',left_on='Codigo_Municipio_2', right_on='cod_municipio')
bd_2024 = bd_2024.merge(clin_Amb_ESP, how='left',left_on='Codigo_Municipio_2', right_on='cod_municipio')

In [1840]:
bd_2024 = bd_2024.merge(leitos_internacao, how='left',left_on='Codigo_Municipio_2', right_on='cod_municipio')

In [1841]:
bd_2024.drop(columns=['cod_municipio', 'cod_municipio_x', 'cod_municipio_y'], inplace=True)

In [1842]:
bd_2024 = bd_2024.merge(leitos_repouso_Ambulatorio_FEM, how='left',left_on='Codigo_Municipio_2', right_on='cod_municipio')
bd_2024 = bd_2024.merge(leitos_repouso_Ambulatorio_MASC, how='left',left_on='Codigo_Municipio_2', right_on='cod_municipio')
bd_2024 = bd_2024.merge(leitos_repouso_Ambulatorio_INDF, how='left',left_on='Codigo_Municipio_2', right_on='cod_municipio')
bd_2024.drop(columns=['cod_municipio', 'cod_municipio_x', 'cod_municipio_y'], inplace=True)
bd_2024 = bd_2024.merge(leitos_repouso_Ambulatorio_PED, how='left',left_on='Codigo_Municipio_2', right_on='cod_municipio')

In [1843]:
bd_2024 = bd_2024.merge(leitos_repouso_Urgencia_FEM, how='left',left_on='Codigo_Municipio_2', right_on='cod_municipio')
bd_2024 = bd_2024.merge(leitos_repouso_Urgencia_MASC, how='left',left_on='Codigo_Municipio_2', right_on='cod_municipio')
bd_2024.drop(columns=['cod_municipio', 'cod_municipio_x', 'cod_municipio_y'], inplace=True)
bd_2024 = bd_2024.merge(leitos_repouso_Urgencia_INDF, how='left',left_on='Codigo_Municipio_2', right_on='cod_municipio')
bd_2024 = bd_2024.merge(leitos_repouso_Urgencia_PED, how='left',left_on='Codigo_Municipio_2', right_on='cod_municipio')
bd_2024.drop(columns=['cod_municipio_x', 'cod_municipio_y'], inplace=True)

In [1844]:
bd_2024 = bd_2024.merge(bpc, how='left', left_on='Codigo_Municipio_2', right_on='ibge')

In [1845]:
bd_2024 = bd_2024.drop('ibge', axis=1)

In [1846]:
bd_2024 = bd_2024.merge(bolsa_familia, how='left', left_on='Codigo_Municipio_2', right_on='ibge')

In [1847]:
bd_2024 = bd_2024.drop('ibge', axis=1)

In [1848]:
bd_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 35 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Codigo_Municipio                               5570 non-null   int64
 1   Codigo_Municipio_2                             5570 non-null   int64
 2   Município                                      5570 non-null   object
 3   UF                                             5570 non-null   int64
 4   Sigla_UF                                       5570 non-null   object
 5   2024_Estoque_media                             5464 non-null   float64
 6   2024_Estoque_MAX                               5464 non-null   float64
 7   2024_Estoque_MIN                               5464 non-null   float64
 8   Numero Clinicas de Ambulatorio Basicas         5320 non-null   float64
 9   Numero Clinicas de Ambulatorio Especializadas  4033 non-null   float64
 10  Numero Leitos de Internação                    3552 non-null   float64
 11  Numero Leitos de Ambulatorio Feminino          1500 non-null   float64
 12  Numero Leitos de Ambulatorio Masculino         3591 non-null   float64
 13  Numero Leitos de Ambulatorio Indiferente       3591 non-null   float64
 14  Numero Leitos de Ambulatorio Pediatro          3591 non-null   float64
 15  Numero Leitos de Urgencia Feminino             2427 non-null   float64
 16  Numero Leitos de Urgencia Masculino            2367 non-null   float64
 17  Numero Leitos de Urgencia Indiferente          2470 non-null   float64
 18  Numero Leitos de Urgencia Pediatro             2367 non-null   float64
 19  num_beneficiados_bpc                           5464 non-null   float64
 20  media_beneficiados_bpc                         5464 non-null   float64
 21  num_pcd_beneficiados_bpc                       5464 non-null   float64
 22  media_pcd_beneficiados_bpc                     5464 non-null   float64
 23  num_idoso_beneficiados_bpc                     5464 non-null   float64
 24  media_idoso_beneficiados_bpc                   5464 non-null   float64
 25  valor_total_repassado_bpc                      5464 non-null   float64
 26  media_valor_repassado_bpc                      5464 non-null   float64
 27  valor_pcd_repassado_bpc                        5464 non-null   float64
 28  media_valor_pcd_repassado_bpc                  5464 non-null   float64
 29  valor_idoso_repassado_bpc                      5464 non-null   float64
 30  media_valor_idoso_repassado_pbc                5464 non-null   float64
 31  qtd_familias_total_bolsa_familia               5464 non-null   float64
 32  media_qtd_familias_bolsa_familia               5464 non-null   float64
 33  valor_total_repassado_bolsa_familia            5464 non-null   float64
 34  media_valor_repassado_bolsa_familia            5464 non-null   float64
dtypes: float64(30), int64(3), object(2)
memory usage: 1.5+ MB

In [1849]:
bd_2024.describe()

,Codigo_Municipio,Codigo_Municipio_2,UF,2024_Estoque_media,2024_Estoque_MAX,2024_Estoque_MIN,Numero Clinicas de Ambulatorio Basicas,Numero Clinicas de Ambulatorio Especializadas,Numero Leitos de Internação,Numero Leitos de Ambulatorio Feminino,...,valor_total_repassado_bpc,media_valor_repassado_bpc,valor_pcd_repassado_bpc,media_valor_pcd_repassado_bpc,valor_idoso_repassado_bpc,media_valor_idoso_repassado_pbc,qtd_familias_total_bolsa_familia,media_qtd_familias_bolsa_familia,valor_total_repassado_bolsa_familia,media_valor_repassado_bolsa_familia
count,"5,570.00","5,570.00","5,570.00","5,464.00","5,464.00","5,464.00","5,320.00","4,033.00","3,552.00","1,500.00",...,"5,464.00","5,464.00","5,464.00","5,464.00","5,464.00","5,464.00","5,464.00","5,464.00","5,464.00","5,464.00"
mean,"3,253,590.77","319,572.75",32.38,"8,308.95","8,347.47","8,270.44",484.31,631.99,"1,515.90",58.99,...,"13,703,153.64","1,245,741.24","7,598,716.88","844,307.04","6,104,436.77","678,275.69","41,377.64","3,761.60","28,182,472.59","2,562,042.96"
std,"984,910.34","107,233.03",9.83,"79,093.91","79,337.52","78,850.38","3,442.10","4,805.45","8,785.20",97.57,...,"74,965,565.02","6,815,051.37","32,971,870.16","3,663,540.03","42,872,745.19","4,763,637.67","178,850.07","16,259.10","119,807,967.07","10,891,633.37"
min,"1,100,015.00",0.00,11.00,3.00,3.00,3.00,1.00,1.00,2.00,1.00,...,"14,120.00","1,283.64","14,120.00","1,568.89",0.00,0.00,101.00,9.18,"65,597.00","5,963.36"
25%,"2,512,125.75","250,562.50",25.00,280.50,284.00,278.00,48.00,24.00,228.00,24.00,...,"1,070,326.11","97,302.37","738,483.06","82,053.68","268,280.38","29,808.93","5,616.75",510.62,"3,742,709.25","340,246.30"
50%,"3,146,280.00","314,255.00",31.00,879.50,887.00,872.00,108.50,60.00,416.00,36.00,...,"2,994,249.56","272,204.51","1,977,581.09","219,731.23","875,443.84","97,271.54","14,577.50","1,325.22","9,918,314.00","901,664.91"
75%,"4,119,189.50","411,757.50",41.00,"3,123.00","3,151.00","3,112.00",269.00,219.00,813.00,60.00,...,"9,038,019.83","821,638.17","5,803,575.60","644,841.73","3,038,287.48","337,587.50","36,446.50","3,313.32","25,006,877.75","2,273,352.52"
max,"5,300,108.00","530,010.00",53.00,"4,808,540.00","4,823,699.00","4,793,381.00","171,511.00","229,885.00","366,311.00","1,903.00",...,"3,431,670,178.52","311,970,016.23","1,301,486,793.30","144,609,643.70","2,130,183,385.22","236,687,042.80","7,731,744.00","702,885.82","5,164,847,171.00","469,531,561.00"

In [1850]:
bd_2024

,Codigo_Municipio,Codigo_Municipio_2,Município,UF,Sigla_UF,2024_Estoque_media,2024_Estoque_MAX,2024_Estoque_MIN,Numero Clinicas de Ambulatorio Basicas,Numero Clinicas de Ambulatorio Especializadas,...,valor_total_repassado_bpc,media_valor_repassado_bpc,valor_pcd_repassado_bpc,media_valor_pcd_repassado_bpc,valor_idoso_repassado_bpc,media_valor_idoso_repassado_pbc,qtd_familias_total_bolsa_familia,media_qtd_familias_bolsa_familia,valor_total_repassado_bolsa_familia,media_valor_repassado_bolsa_familia
0,1100015,110001,Alta Floresta D'Oeste,11,RO,"2,294.00","2,298.00","2,290.00",453.00,84.00,...,"7,757,639.41","705,239.95","6,328,691.21","703,187.91","1,428,948.20","158,772.02","18,616.00","1,692.36","12,804,296.00","1,164,026.91"
1,1100379,110037,Alto Alegre dos Parecis,11,RO,692.00,700.00,684.00,108.00,24.00,...,"1,434,612.00","130,419.27","1,218,576.00","135,397.33","216,036.00","24,004.00","5,640.00",512.73,"3,520,181.00","320,016.45"
2,1100403,110040,Alto Paraíso,11,RO,"1,247.00","1,255.00","1,239.00",14.00,23.00,...,"6,410,587.96","582,780.72","4,563,677.11","507,075.23","1,846,910.85","205,212.32","13,942.00","1,267.45","9,511,442.00","864,676.55"
3,1100346,110034,Alvorada D'Oeste,11,RO,867.00,869.00,865.00,86.00,60.00,...,"4,793,767.98","435,797.09","3,743,239.98","415,915.55","1,050,528.00","116,725.33","15,870.00","1,442.73","10,835,689.00","985,062.64"
4,1100023,110002,Ariquemes,11,RO,"19,150.00","19,500.00","18,800.00","1,024.00","1,251.00",...,"46,054,015.71","4,186,728.70","30,236,667.06","3,359,629.67","15,817,348.65","1,757,483.18","79,740.00","7,249.09","54,233,194.00","4,930,290.36"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,5222005,522200,Vianópolis,52,GO,"2,972.00","2,980.00","2,964.00",36.00,24.00,...,"4,827,666.78","438,878.80","2,774,608.36","308,289.82","2,053,058.42","228,117.60","11,734.00","1,066.73","7,995,392.00","726,853.82"
5566,5222054,522205,Vicentinópolis,52,GO,"2,311.50","2,361.00","2,262.00",120.00,NaN,...,"1,883,670.80","171,242.80","1,236,966.15","137,440.68","646,704.65","71,856.07","8,911.00",810.09,"6,056,026.00","550,547.82"
5567,5222203,522220,Vila Boa,52,GO,"1,410.00","1,422.00","1,398.00",72.00,NaN,...,"1,813,021.34","164,820.12","1,379,534.34","153,281.59","433,487.00","48,165.22","7,015.00",637.73,"4,807,678.00","437,061.64"
5568,5222302,522230,Vila Propício,52,GO,"1,146.00","1,158.00","1,134.00",24.00,NaN,...,"653,769.49","59,433.59","532,333.89","59,148.21","121,435.60","13,492.84","8,348.00",758.91,"5,564,729.00","505,884.45"
5569,5300108,530010,Brasília,53,DF,"973,895.50","977,151.00","970,640.00","30,448.00","73,932.00",...,"914,960,165.59","83,178,196.87","487,748,691.92","54,194,299.10","427,211,473.67","47,467,941.52","2,032,446.00","184,767.82","1,390,106,282.00","126,373,298.36"